# Generated by Django 4.2 on 2023-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('diameter', models.FloatField(unique=True)),
            ],
        ),
    ]
