# Generated by Django 4.2 on 2023-04-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('diameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibers', to='ebalapi_service.diameter')),
            ],
        ),
    ]
