# Generated by Django 4.2 on 2023-04-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0002_caliber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('weight', models.FloatField(default=0.168)),
                ('length', models.FloatField(default=1.2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('drag_function_type', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7'), ('G8', 'G8'), ('GS', 'GS'), ('GC', 'GC'), ('G1_MULTI_BC', 'G1_MULTI_BC'), ('G7_MULTI_BC', 'G7_MULTI_BC'), ('CUSTOM', 'CUSTOM')], default='G7', max_length=20)),
                ('drag_function_data', models.TextField()),
                ('diameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bullets', to='ebalapi_service.diameter')),
            ],
        ),
    ]
