# Generated by Django 4.2 on 2023-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0003_bullet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='drag_function_data',
            field=models.JSONField(),
        ),
    ]
