# Generated by Django 4.2 on 2023-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0005_cartridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='muzzle_velocity',
            field=models.FloatField(default=800),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='temperature',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='temperature_sensitivity',
            field=models.JSONField(default='{15: 800, 0: 790}'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='drag_function_data',
            field=models.JSONField(default='{"value", 0.175}'),
        ),
    ]
