# Generated by Django 4.2 on 2023-04-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0006_cartridge_muzzle_velocity_cartridge_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='drag_function_data',
            field=models.JSONField(default={'value': 0.175}),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='temperature_sensitivity',
            field=models.JSONField(default=[[15, 800], [0, 790]]),
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('barrel_length', models.FloatField(default=61)),
                ('rail_angle', models.FloatField(default=20)),
                ('twist_rate', models.FloatField(default=10)),
                ('twist_direction', models.IntegerField(choices=[(1, 'Right'), (2, 'Left')], default=1, max_length=20)),
                ('caliber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifles', to='ebalapi_service.caliber')),
            ],
        ),
    ]
