# Generated by Django 4.2 on 2023-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0007_cartridge_comment_alter_bullet_drag_function_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='drag_function_type',
            field=models.CharField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G5'), (4, 'G6'), (5, 'G7'), (6, 'G8'), (7, 'GS'), (8, 'GC'), (9, 'G1_MULTI_BC'), (10, 'G7_MULTI_BC'), (11, 'CUSTOM')], default=5, max_length=20),
        ),
    ]
