# Generated by Django 4.2 on 2023-04-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0008_alter_bullet_drag_function_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bullet',
            name='drag_function_type',
            field=models.CharField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G5'), (4, 'G6'), (5, 'G7'), (6, 'G8'), (7, 'GS'), (8, 'GC'), (9, 'G1 MULTI BC'), (10, 'G7 MULTI BC'), (11, 'CUSTOM')], default=5, max_length=20),
        ),
        migrations.AddField(
            model_name='bullet',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bullets', to='ebalapi_service.bulletvendor'),
        ),
    ]
