# Generated by Django 4.2 on 2023-04-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0009_bulletvendor_alter_bullet_drag_function_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RifleVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rifle',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifles', to='ebalapi_service.riflevendor'),
        ),
    ]
