# Generated by Django 4.2 on 2023-04-06 11:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0012_alter_bullet_drag_function_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='caliber', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridges', to='ebalapi_service.bullet'),
        ),
    ]
