# Generated by Django 4.2 on 2023-04-06 11:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0013_alter_cartridge_bullet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=smart_selects.db_fields.GroupedForeignKey(default=0, group_field='caliber', on_delete=django.db.models.deletion.CASCADE, to='ebalapi_service.bullet'),
            preserve_default=False,
        ),
    ]
