# Generated by Django 4.2 on 2023-04-06 11:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0016_alter_cartridge_bullet_alter_cartridge_caliber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='diameter', on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='ebalapi_service.bullet'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='caliber',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='diameter', on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='ebalapi_service.caliber'),
        ),
    ]
