# Generated by Django 4.2 on 2023-04-06 11:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0017_alter_cartridge_bullet_alter_cartridge_caliber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='diameter',
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='diameter', chained_model_field='caliber.diameter', on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='ebalapi_service.bullet'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='caliber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridges', to='ebalapi_service.caliber'),
        ),
    ]
