# Generated by Django 4.2 on 2023-04-06 11:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0018_remove_cartridge_diameter_alter_cartridge_bullet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='caliber', chained_model_field='caliber.diameter', on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='ebalapi_service.bullet'),
        ),
    ]
