# Generated by Django 4.2 on 2023-04-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0019_alter_cartridge_bullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullet',
            name='drag_function_data',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='drag_function_type',
        ),
        migrations.AddField(
            model_name='bullet',
            name='g1',
            field=models.FloatField(blank=True, default=0.168, null=True),
        ),
        migrations.AddField(
            model_name='bullet',
            name='g7',
            field=models.FloatField(blank=True, default=0.168, null=True),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='bullet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridges', to='ebalapi_service.bullet'),
        ),
        migrations.CreateModel(
            name='DragFunction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('drag_function_type', models.IntegerField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G5'), (4, 'G6'), (5, 'G7'), (6, 'G8'), (7, 'GS'), (8, 'GC'), (9, 'G1 MULTI BC'), (10, 'G7 MULTI BC'), (11, 'CUSTOM')], default=5, max_length=20)),
                ('drag_function_data', models.JSONField(default={'value': 0.175})),
                ('bullet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drag_functions', to='ebalapi_service.bullet')),
            ],
        ),
    ]
