# Generated by Django 4.2 on 2023-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0020_remove_bullet_drag_function_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragfunction',
            old_name='drag_function_data',
            new_name='df_data',
        ),
        migrations.RemoveField(
            model_name='dragfunction',
            name='drag_function_type',
        ),
        migrations.AddField(
            model_name='dragfunction',
            name='df_type',
            field=models.IntegerField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G5'), (4, 'G6'), (5, 'G7'), (6, 'G8'), (7, 'GS'), (8, 'GC'), (9, 'G1 MULTI BC'), (10, 'G7 MULTI BC'), (11, 'CUSTOM')], default=5),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='twist_direction',
            field=models.IntegerField(choices=[(1, 'Right'), (2, 'Left')], default=1),
        ),
    ]
