# Generated by Django 4.2 on 2023-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0024_vendor_alter_rifle_rail_angle_alter_bullet_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='temperature_sensitivity',
            field=models.JSONField(blank=True, default=[[15, 800], [0, 790]], null=True),
        ),
    ]
