# Generated by Django 4.2 on 2023-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0025_alter_cartridge_temperature_sensitivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='temperature_sensitivity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
