# Generated by Django 4.2 on 2023-04-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0026_alter_bullet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragfunction',
            name='name',
        ),
    ]
