# Generated by Django 4.2 on 2023-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0027_remove_dragfunction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
