# Generated by Django 4.2 on 2023-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0028_bullet_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='metadata',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
