# Generated by Django 4.2 on 2023-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebalapi_service', '0029_alter_bullet_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='comment_no_punc',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='bullet',
            name='name_no_punc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
